version: "3.7"

services:
  archivebox:
    image: mongo-express
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/mongo-express:/data
    ports:
      - "8081:8000"
    environment:
      ALLOWED_HOSTS: "*"
      USE_COLOR: "True"
