version: "3.7"

services:
  archivebox:
    image: postgres
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/postgres:/data
    ports:
      - "8767:8001"
    environment:
      ALLOWED_HOSTS: "*"
      USE_COLOR: "True"
