services:

  postgresdb:
    image: postgres
    restart: always
    shm_size: 128mb    
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $APP_PASSWORD
    ports:
      - 1769:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb

