version: '3.8'

services:
app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: tpr-mongoexpress_1
      APP_PORT: 8081

  mongo:
    image: mongo:4
    restart: always

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: always