version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Berlin/Europe
    ports:
        - "8500:8000" # HTTP
        - "8543:8443" # HTTPS
        - "8523:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ${APP_DATA_DIR}/data/tpr-crafty/backups:/crafty/backups
        - ${APP_DATA_DIR}/data/tpr-crafty/logs:/crafty/logs
        - ${APP_DATA_DIR}/data/tpr-crafty/servers:/crafty/servers
        - ${APP_DATA_DIR}/data/tpr-crafty/app/config:/crafty/app/config
        - ${APP_DATA_DIR}/data/tpr-crafty/import:/crafty/import